# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

WORKDIR /app

# Copy package.json and install dependencies
COPY package.json .
RUN npm install --ignore-scripts

# Copy rest of the application
COPY . .

# Expose any ports if needed (none specified)

CMD ["node", "index.js"]
